import * as React from "react";
import {
  View,
  ScrollView,
  KeyboardAvoidingView,
  Platform,
  Alert,
  ActivityIndicator,
  TouchableOpacity,
  TextInput,
  Pressable,
} from "react-native";
import { useRouter, useLocalSearchParams } from "expo-router";
import { Mail, AlertCircle, CheckCircle } from "lucide-react-native";
import { Ionicons } from "@expo/vector-icons";

import { SafeAreaView } from "@/components/safe-area-view";
import { Text } from "@/components/ui/text";
import { H1, P } from "@/components/ui/typography";
import { useAuth } from "@/context/supabase-provider";
import { useColorScheme } from "@/lib/useColorScheme";
import { supabase } from "@/config/supabase";
import { mapAuthError } from "@/lib/authErrors";

export default function VerifyEmailOTP() {
  const { colorScheme } = useColorScheme();
  const router = useRouter();
  const params = useLocalSearchParams<{ email: string }>();
  const email = params.email;
  const { setPostAuthNavigation } = useAuth();

  const [otp, setOtp] = React.useState("");
  const [loading, setLoading] = React.useState(false);
  const [resending, setResending] = React.useState(false);
  const [error, setError] = React.useState("");
  const [resendCooldown, setResendCooldown] = React.useState(0);
  const cooldownTimerRef = React.useRef<ReturnType<typeof setInterval> | null>(
    null,
  );

  const isDark = colorScheme === "dark";

  // Cooldown timer effect
  React.useEffect(() => {
    if (resendCooldown > 0) {
      cooldownTimerRef.current = setInterval(() => {
        setResendCooldown((prev) => {
          if (prev <= 1) {
            if (cooldownTimerRef.current) {
              clearInterval(cooldownTimerRef.current);
              cooldownTimerRef.current = null;
            }
            return 0;
          }
          return prev - 1;
        });
      }, 1000);
    }

    return () => {
      if (cooldownTimerRef.current) {
        clearInterval(cooldownTimerRef.current);
        cooldownTimerRef.current = null;
      }
    };
  }, [resendCooldown]);

  const handleVerifyOTP = async (): Promise<void> => {
    if (!otp || otp.length !== 6) {
      setError("Please enter the 6-digit code");
      return;
    }

    if (!email) {
      setError("Email address is missing. Please try signing up again.");
      return;
    }

    try {
      setLoading(true);
      setError("");

      // Redirect to complete-profile after OTP verification instead of home
      setPostAuthNavigation("/complete-profile");

      // Verify the OTP using Supabase Auth.
      // type: "signup" matches the token generated by signUp() / generateLink({ type: 'signup' })
      const { data, error: verifyError } = await supabase.auth.verifyOtp({
        email,
        token: otp,
        type: "signup",
      });

      if (verifyError) {
        throw verifyError;
      }

      if (!data.session) {
        throw new Error("No session created after verification");
      }

      // Success! The auth provider will automatically navigate the user
      // No need to manually navigate - the auth flow handles this
      Alert.alert(
        "Email Verified!",
        "Your email has been verified successfully. Setting up your account...",
        [
          {
            text: "OK",
          },
        ],
      );
    } catch (error: any) {
      console.error("Email OTP verification error:", error);
      const mapped = mapAuthError(error);
      setError(mapped.message);
    } finally {
      setLoading(false);
    }
  };

  const handleResendOTP = async (): Promise<void> => {
    if (resendCooldown > 0) {
      setError(`Please wait ${resendCooldown} seconds before resending`);
      return;
    }

    if (!email) {
      setError("Email address is missing. Please try signing up again.");
      return;
    }

    try {
      setResending(true);
      setError("");

      // Use Supabase's built-in resend — re-sends the confirmation email with a fresh OTP token.
      const { error: resendError } = await supabase.auth.resend({
        type: "signup",
        email,
      });

      if (resendError) {
        throw resendError;
      }

      // Clear OTP input
      setOtp("");

      // Start cooldown (60 seconds)
      setResendCooldown(60);

      Alert.alert(
        "Code Resent",
        `A new verification code has been sent to ${email}`,
        [{ text: "OK" }],
      );
    } catch (error: any) {
      console.error("Resend OTP error:", error);
      const mapped = mapAuthError(error);
      setError(mapped.message);
    } finally {
      setResending(false);
    }
  };

  const handleGoBack = (): void => {
    Alert.alert(
      "Exit Verification?",
      "You'll need to verify your email to activate your account. You can complete this later by clicking the link in your email.",
      [
        { text: "Stay", style: "cancel" },
        {
          text: "Exit",
          onPress: () => {
            router.replace("/sign-in");
          },
        },
      ],
    );
  };

  return (
    <SafeAreaView className="flex-1 bg-primary" edges={["top", "bottom"]}>
      {/* Fixed Header */}
      <View className="p-4 pb-2">
        <View className="flex-row items-center">
          <TouchableOpacity
            onPress={handleGoBack}
            className="mr-4 p-2"
            hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
          >
            <Ionicons
              name="arrow-back"
              size={24}
              color={isDark ? "#fff" : "#000"}
            />
          </TouchableOpacity>
          <View className="flex-1">
            <H1 className="self-start text-white">Verify Your Email</H1>
            <P className="text-white/90 mt-2">
              We've sent a verification code to your email
            </P>
          </View>
        </View>
      </View>

      <KeyboardAvoidingView
        behavior={Platform.OS === "ios" ? "padding" : "height"}
        className="flex-1"
      >
        <ScrollView
          contentContainerStyle={{ flexGrow: 1, paddingHorizontal: 16 }}
          keyboardShouldPersistTaps="handled"
        >
          <View className="flex-1 gap-6 py-8">
            {/* Icon */}
            <View className="items-center">
              <View className="w-20 h-20 rounded-full bg-white/20 items-center justify-center">
                <Mail size={40} color="#fff" />
              </View>
            </View>

            {/* Email Display */}
            <View className="bg-white/10 rounded-lg p-4">
              <Text className="text-sm text-center text-white/70">
                Code sent to
              </Text>
              <Text className="text-center font-medium mt-1 text-white text-base">
                {email}
              </Text>
            </View>

            {/* OTP Input */}
            <View>
              <Text className="text-sm font-medium mb-2 text-white">
                Verification Code
              </Text>
              <TextInput
                value={otp}
                onChangeText={(text) => {
                  setOtp(text.replace(/[^0-9]/g, ""));
                  setError("");
                }}
                placeholder="000000"
                placeholderTextColor={isDark ? "#666" : "#999"}
                keyboardType="number-pad"
                maxLength={6}
                className="py-4 px-4 bg-gray-100 dark:bg-gray-800 border-2 border-input rounded-lg text-foreground text-center text-2xl tracking-widest"
                editable={!loading}
                autoFocus
                returnKeyType="done"
                onSubmitEditing={handleVerifyOTP}
              />
              <Text className="text-xs text-white/70 mt-2 text-center">
                Enter the 6-digit code sent to your email
              </Text>
            </View>

            {/* Error Message */}
            {error && (
              <View className="flex-row items-center gap-2 p-3 bg-red-50 dark:bg-red-950/30 rounded-lg">
                <AlertCircle size={20} color="#ef4444" />
                <Text className="flex-1 text-sm text-red-600 dark:text-red-400">
                  {error}
                </Text>
              </View>
            )}

            {/* Resend Button */}
            <View className="items-center">
              <Pressable
                onPress={handleResendOTP}
                disabled={resending || resendCooldown > 0}
                style={({ pressed }) => ({
                  opacity: pressed || resending || resendCooldown > 0 ? 0.6 : 1,
                })}
              >
                {resending ? (
                  <View className="flex-row items-center gap-2">
                    <ActivityIndicator size="small" color="#fff" />
                    <Text className="text-white">Sending...</Text>
                  </View>
                ) : resendCooldown > 0 ? (
                  <Text className="text-white/70">
                    Resend code in {resendCooldown}s
                  </Text>
                ) : (
                  <Text className="text-white font-medium">
                    Didn't receive the code? Resend
                  </Text>
                )}
              </Pressable>
            </View>
          </View>

          {/* Verify Button */}
          <View className="p-4">
            <TouchableOpacity
              onPress={handleVerifyOTP}
              disabled={loading || otp.length !== 6}
              className={`h-14 rounded-lg items-center justify-center ${
                loading || otp.length !== 6 ? "opacity-50" : ""
              }`}
              activeOpacity={0.7}
              style={{
                backgroundColor: "#000",
                borderWidth: 1,
                borderColor: "rgba(255,255,255,0.12)",
                shadowColor: "#000",
                shadowOpacity: 0.12,
                shadowRadius: 8,
                shadowOffset: { width: 0, height: 2 },
                elevation: 2,
              }}
            >
              {loading ? (
                <ActivityIndicator size="small" color="white" />
              ) : (
                <Text className="font-medium text-white">Verify Email</Text>
              )}
            </TouchableOpacity>
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}
