// app/layout.tsx
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { headers } from "next/headers"
import "./globals.css"
import { Toaster } from "react-hot-toast"
import { Toaster as SonnerToaster } from "sonner"
import { Providers } from "@/components/provider"
import { PWAProvider } from "@/components/pwa/pwa-provider"
import { NotificationProvider } from "@/lib/contexts/notification-context"
import { NotificationContainer } from "@/components/notifications/notification-container"
import { AppVisibilityHandler } from "@/components/pwa/app-visibility-handler"
 
// import { Analytics } from "@vercel/analytics/next"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "ForkCast Management",
  description: "Complete restaurant management system for ForkCast",
  // manifest is auto-generated by app/manifest.ts at /manifest.webmanifest
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'ForkCast Management',
  },
  icons: {
    icon: [
      { url: '/icon-192x192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icon-384x384.png', sizes: '384x384', type: 'image/png' },
      { url: '/icon-512x512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: [
      { url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
    ],
  },
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Nonce is set per-request in middleware.ts and forwarded via request
  // headers. Passing it to next-themes so its anti-flash inline script
  // complies with our strict-dynamic CSP (pentest W11).
  const nonce = (await headers()).get('x-nonce') ?? undefined
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover, orientation=landscape" />
        <meta name="theme-color" content="#7A2E4A" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="ForkCast Management" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="application-name" content="ForkCast Management" />
        <meta name="msapplication-TileColor" content="#7A2E4A" />
        <meta name="msapplication-config" content="none" />
        <meta name="screen-orientation" content="landscape" />
        <meta name="orientation" content="landscape" />
        {/* manifest link is auto-generated by Next.js from app/manifest.ts */}
        <link rel="icon" type="image/png" sizes="192x192" href="/icon-192x192.png" />
        <link rel="icon" type="image/png" sizes="384x384" href="/icon-384x384.png" />
        <link rel="icon" type="image/png" sizes="512x512" href="/icon-512x512.png" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
      </head>
      <body className={inter.className} suppressHydrationWarning>
        <Providers nonce={nonce}>
          <PWAProvider>
            <NotificationProvider>
              <AppVisibilityHandler />
              {children}
              {/* Hide notification container on admin routes to avoid showing toasts in admin */}
              {/* This is a client layout; NotificationContainer internally reads context. We'll conditionally render in a thin client wrapper */}
              <NotificationContainer />
              <Toaster position="top-center" />
              <SonnerToaster richColors position="top-center" />
              {/* <Analytics /> */}
            </NotificationProvider>
          </PWAProvider>
        </Providers>
      </body>
    </html>
  )
}
